id = "maya"
name = "Maya Theme"
version = "0.4.6"
schema_version = 1
authors = ["Sean Bowman <pico303@gmail.com>"]
description = "A dark theme based on years of tweaking."
repository = "https://github.com/sbowman/maya.zed"
